version: "3"

services:
  operativeai-app:
    extends:
      file: ./app/docker-compose.yml
      service: operativeai-app
    environment:
      - VITE_SERVICE_URL=${API_HOST}:${API_PORT}
      - APP_PORT=${APP_PORT}
    env_file:
      - path: .env.default
        required: true
      - path: .env
        required: false

  operativeai-api:
    extends:
      file: ./api/docker-compose.yml
      service: operativeai-api
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_HOST}:${OLLAMA_PORT}
      - API_PORT=${API_PORT}
    env_file:
      - path: .env.default
        required: true
      - path: .env
        required: false

  chromadb:
    extends:
      file: ./api/docker-compose.yml
      service: chromadb
