version: "3"

services:
  operativeai-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./index.html:/usr/src/app/index.html
