version: "3"

services:
  operativeai-api:
    build: .
    ports:
      - "${API_PORT}:4000"
    volumes:
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
      - ./tsconfig.json:/usr/src/app/tsconfig.json
  chromadb:
    image: chromadb/chroma
    ports:
      - "${RAG_DB_PORT}:8000"
    volumes:
      - ./.db/chromadb/data:/var/lib/chromadb/data
